### PR TITLE
adding function to check lengths can be combined into each other without recycling (except length 1)

### PR DESCRIPTION
**Pull request by aylapear**
- commits are mixed with main branch due to not making feature branch at the beginning
- adding `chk_lengths_into()` and `vld_lengths_into()` function to check if vectors can be combined together in cases where the lengths should be the same
- this can be helpful in situations like when pasting together hours and minutes together to make time values.
- testing provided for each function and case 
- tests and R CMD checks all passing 
- styler ran
- rendered readme 
- pkgdown site generates

### CODE REVIEW

**Comment by aylapear** [comment]
Wait to see if/which version of R fail with the `lengths()` function before working out best fix

**Comment by aylapear** [comment]
The `lengths()` function has been around long enough that none of our checks on older versions failed so no need to change or to use backports to fix version issues.

**Comment by joethorley** [comment]
I've made some tweaks - @aylapear can you review them?

**Review by joethorley — APPROVED** [review]
Looks awesome

**Pull request merged**
